#!/bin/sh
### BEGIN INIT INFO
# Provides:          cpu-mem
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       output the cpu and memory to a file
### END INIT INFO

RUNAS=root

PIDFILE=/var/run/custom-service.pid
LOGFILE=/var/log/custom-service.log

COMMAND='while true; do [[ $(date +"%H") > 20 ]] && echo $(uptime) $(free -m | grep cache:); [[ $(date +"%H.%M") < 01.29 ]] && echo $(uptime) $(free -m | grep cache:); [[ $(date +"%H.%M") = 01.26 && -f '$LOGFILE' ]] && rm -f '$LOGFILE'; sleep 10; done'

COMMAND='while true; do [[ $(date +"%H") > 20 || $(date +"%H") < 08 ]] && echo $(uptime) $(free -m | grep cache:); [[ $(date +"%H") = 08 && -s '$LOGFILE' ]] && cp '$LOGFILE' /tmp/cpu-mem.csv && cat /dev/null > '$LOGFILE'; [[ $(date +"%H") < 20 || $(date +"%H") > 08 ]] && sleep 3000; sleep 60; done'

COMMAND='while true; do echo $(uptime) $(free -m | grep cache:); [[ $(date +"%H") = 08 && -s '$LOGFILE' ]] && cp '$LOGFILE' /tmp/cpu-mem.csv && cat /dev/null > '$LOGFILE'; sleep 150; done'

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting custom service…' >&2
  local CMD="$COMMAND &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping custom service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f <NAME> remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
